# Generated by Django 5.0 on 2023-12-13 18:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_client_address_apartament_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_city',
            field=models.CharField(default='Rzeszów', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2005, 12, 17))]),
        ),
    ]
