# Generated by Django 5.0 on 2024-01-02 16:50

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_order_set_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2006, 1, 6))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_set_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 17, 50, 7, 244162)),
        ),
        migrations.CreateModel(
            name='WineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.wine')),
            ],
        ),
    ]
