# Generated by Django 5.0 on 2024-01-02 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_client_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='wines',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_set_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 17, 54, 34, 10245)),
        ),
    ]
