# Generated by Django 5.0 on 2024-01-13 11:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_order_wines_alter_order_order_set_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wineorder',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2006, 1, 17))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_set_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 12, 58, 26, 264346)),
        ),
    ]
